### PR TITLE
Environment variables

### PR DESCRIPTION
**Pull request by ellesmith88**
Updating dask environment variables - these are set in clisops - PR in clisops to follow

### CODE REVIEW

**Review by cehbrecht — APPROVED** [review]
Looks good to me. Not sure why python 3.8 test failed ... restarted.

**Comment by ellesmith88** [comment]
@cehbrecht Thanks. I thought the same, I couldn't work out how to restart it.

**Comment by cehbrecht** [comment]
> @cehbrecht Thanks. I thought the same, I couldn't work out how to restart it.

... just go to travis, login with github and then there is an option to restart the build

**Comment by ellesmith88** [comment]
> ... just go to travis, login with github and then there is an option to restart the build

It's weird - I have that option on travis-ci.com but not travis-ci.org

**Pull request merged**
