### PR TITLE
Esgf test data fix

### PR DESCRIPTION
**Pull request by jhaigh0**
Removed need for esgf data archive submodule, data is now downloaded and cached when a test is run the requires it.

### CODE REVIEW

**Comment by ellesmith88** [comment]
@agstephens @jhaigh0 I'm resolving the conflicts on this and have deleted the submodule and have found that some of the tests aren't working for me - saying `OSError: no files to open` in some of the cases where `load_test_data` is being used.  I think only in the cases where `CMIP6_SICONC` and `C3S_CMIP5_TAS` are used. Any ideas what's going on here?

**Comment by ellesmith88** [comment]
> @agstephens @jhaigh0 I'm resolving the conflicts on this and have deleted the submodule and have found that some of the tests aren't working for me - saying `OSError: no files to open` in some of the cases where `load_test_data` is being used. I think only in the cases where `CMIP6_SICONC` and `C3S_CMIP5_TAS` are used. Any ideas what's going on here?

Looking in the cached `.mini-esgf-data` directory thats been created, not all the expected data is theree

**Comment by jhaigh0** [comment]
@ellesmith88 Hmm not too sure. I'd suggest doing;
```bash
rm -rf /root/.mini-esgf-data/
python -m pytest tests/
```
and see what happens. When I run this on my local version of `esgf-test-data-fix`, all the tests pass and I think it was the same for @agstephens

**Comment by ellesmith88** [comment]
> @ellesmith88 Hmm not too sure. I'd suggest doing;
> 
> ```shell
> rm -rf /root/.mini-esgf-data/
> python -m pytest tests/
> ```
> 
> and see what happens. When I run this on my local version of `esgf-test-data-fix`, all the tests pass and I think it was the same for @agstephens

Thanks - deleting the directory first solved it

**Pull request merged**
