### PR TITLE
C3s mapper

### PR DESCRIPTION
**Pull request by ellesmith88**
This is in relation to the issue https://github.com/roocs/34e-mngmt/issues/75 (**Make sure all repos use a mapping function between path and ds_id within roocs-utils**) 

The `DatasetMapper` class does not currently work for paths that don't start with a known `base_dir`. For example, when using `workflow` in `rook` the second file to be processed will have a file path such as `/tmp/tmpxi6d78ng/subset_tttaum9d/rlds_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_19850116-20141216.nc` and so sending it through `DatasetMapper` raises an error as it can't identify a project.

I have made changes to account for this in the other packages eg. `daops.consolidate` as well as implementing `open_xr_dataset` in `daops` and `clisops` and I have managed to get everything working but I think it would be better to be able to send everything through the mapper.  Opening PR now to discuss this and for feedback.

### CODE REVIEW

**Comment by agstephens** [comment]
Hi @ellesmith88 , thanks for this work, it'll be really useful when in place. 

Regarding your first issue:

> The DatasetMapper class does not currently work for paths that don't start with a known base_dir. For example, when using workflow in rook the second file to be processed will have a file path such as /tmp/tmpxi6d78ng/subset_tttaum9d/rlds_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_19850116-20141216.nc and so sending it through DatasetMapper raises an error as it can't identify a project.

What I wonder about this use-case is that we might not need a project. Since we are dealing directly with a file, we don't need to do a mapping to get the file path. So I assume that `_deduce_project()` is the part that fails. However, maybe we can accept such a failure and just set it to `None`. Of course, such an action would not work the same if you gave it a dataset identifier that needed mapping to a file path - in that case we _would_ want to raise an Exception from `_deduce_project()`.

**Comment by agstephens** [comment]
@ellesmith88 : can you push your `daops` and `clisops` branches to github as well so that I can review them as a whole. Thanks

**Comment by ellesmith88** [comment]
@agstephens I've opened PRs on `daops`, `clisops` and `rook` with some changes (I'm not sure if the travis tests will pass at the moment)

**Comment by agstephens** [comment]
@ellesmith88 this is looking great. Please wait for @jhaigh0's PR for handling the sub-module. We will merge it into your branch first, and then handle everything in this one PR.

Minor things: please remove comment stubs from my original code such as " # better name??" and a few other comments that I started. They can be cleaned out. Thanks 👍

**Pull request merged**
