### PR TITLE
Catalog maker changes

### PR DESCRIPTION
**Pull request by ellesmith88**
This changes the catalog maker to use a database backend instead of the pickle files.

I've updated the readme, history and docs to reflect these changes.

Not too sure what to do with the abcunit backend dependency (abcunit-backend @ git+https://github.com/cedadev/abcunit-backend.git), should I just keep it in requirements.txt?

### CODE REVIEW

**Comment by cehbrecht** [comment]
@ellesmith88 Only comments ...
* There is a package for abcunit on pypi: https://pypi.org/project/abcunit-backend/
* The catalog maker could be an independent package ... but not relevant for this PR

**Review by cehbrecht — COMMENTED** [review]
Looks good to me ... see inline comments.

**Comment by ellesmith88** [comment]
> * There is a package for abcunit on pypi: https://pypi.org/project/abcunit-backend/

Thanks @cehbrecht of course there is! I've changed to use pypi now.

> * The catalog maker could be an independent package ... but not relevant for this PR

I agree, the catalog maker should be moved to a new package soon.

**Review by agstephens — APPROVED** [review]
@ellesmith88 : looks good to me!

**Pull request merged**
